### ISSUE TITLE
medgen_pubmed_lnk.txt.gzのコンバート時にエラーが発生する

### ISSUE THREAD

**Issue by ghost** [biosciencedbc/rdf-medgen#2]
2022/06/15 自動コンバートにて以下のエラーが発生

> /rdf_converter_medgen.rb:371:in `parse`: invalid byte sequence in
> UTF-8 (ArgumentError)
> from /rdf_converter_medgen.rb:359:in `block in rdf`
> from /rdf_converter_medgen.rb:353:in `open`
> from /rdf_converter_medgen.rb:353:in `rdf`
> from /rdf_converter_medgen.rb:582:in `<main>`
> Failed: NonZeroResultCode: Remote command failed with exit status 1

確認したところ以下のファイルコンバート時にエラーが発生している模様

- medgen_pubmed_lnk.txt.gz
  エラーのあるアーカイブファイル参照先: https://ftp.ncbi.nlm.nih.gov/pub/medgen/
  エラーの発生しているコマンド: ruby /rdf_converter_medgen.rb -p --pubmed medgen_pubmed_lnk.txt > /data/medgen_pubmed_lnk_rdf.ttl
  
 エラーの内容からmedgen_pubmed_lnk.txt.gz にバイト文字列等があり、パース時にエラーが発生していると考えられる

**Comment by mitsuhashi** [comment]
medgen_pubmed_lnk.txt.gz のバイト文字列対応の変更がcommitされたので、次の自動実行が正常終了するかを確認する。
https://github.com/skwsm/rdf_converter_medgen/commit/d8193b88afc3e74c29e25d6de862c4b30404400b

**Comment by mitsuhashi** [comment]
更新されたコンバータが自動的に適用されてエラーも出力されず、turtleファイルも作成されていることも確認しましたのでクローズします。
```
[rdf-medgen_logs]$ cat 20220616_stderr.log
/rdf_converter_medgen.rb:371:in `parse': invalid byte sequence in UTF-8 (ArgumentError)
	from /rdf_converter_medgen.rb:359:in `block in rdf'
	from /rdf_converter_medgen.rb:353:in `open'
	from /rdf_converter_medgen.rb:353:in `rdf'
	from /rdf_converter_medgen.rb:582:in `<main>'
[rdf-medgen_logs]$ cat 20220620_stderr.log
[rdf-medgen_logs]$
```
